name: 'Kubernetes Deploy Action'
description: 'Action used to deploy service to a Kubernetes cluster'
inputs:
  RELEASE_NAME:
    description: 'The name of the release to deploy to kubernetes with'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.RELEASE_NAME }}
